apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: 
contexts:
- context:
    cluster: 
    namespace: 
    user: 
  name: 
current-context: 
kind: Config
preferences: {}
users:
- name: add-custom-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - add-your-region
      - eks
      - get-token
      - --cluster-name
      - add-your-cluster-name
      command: aws
      env:
      - name: AWS_PROFILE
        value: default
      provideClusterInfo: false